# Generated by Django 3.0.6 on 2020-05-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='efficient_percent',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
